version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=https://chatter-api.space
    depends_on:
      - backend