version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    expose:
      - "5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  frontend:
    build: ./client
    container_name: frontend
    expose:
      - "3000"
    environment:
      - VITE_API_URL=https://chatter-api.space