name: Deploy to Oracle Cloud VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: |
            chatter-frontend:latest
            chatter-backend:latest

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/ubuntu/dev/chatter
            git pull origin main
            docker compose down
            docker compose up -d --build
          